include $(GOROOT)/src/Make.inc

TARG=golem
GOFILES=\
	vars.go\
	log.go\
	Connection.go\
	Submission.go\
	controllers_master.go\
	controllers_scribe.go\
	controllers_proxy.go\
	master.go\
	scribe.go\
	control.go\
	jobkiller.go\
	uniqueid.go\
	nodehandle.go\
	rest.go\
	node.go\
	tls.go\
	storage.go\
	storage_mongodb.go\
	entities.go\
	config.go\
	main.go\
	addama.go\
	

include $(GOROOT)/src/Make.cmd