include $(GOROOT)/src/Make.inc

TARG=golem
GOFILES=\
	vars.go\
	log.go\
	password.go\
	WorkerMessage.go\
	Job.go\
	Connection.go\
	Submission.go\
	restOnJob.go\
	controllers.go\
	controllers_scribe.go\
	controllers_proxy.go\
	master.go\
	scribe.go\
	control.go\
	jobkiller.go\
	uniqueid.go\
	nodehandle.go\
	rest.go\
	node.go\
	tls.go\
	storage.go\
	main.go\
	

include $(GOROOT)/src/Make.cmd